name: Test

on:
  push:
    branches: [ main, 'release_*' ]
  pull_request:
    branches: [ main, 'release_*' ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display Go version
      run: go version

    - name: Build
      run: go build

    - name: Test
      run: go test
